"""initial public schema

Revision ID: ef642ea726cd
Revises: 
Create Date: 2026-05-01 17:17:51.160575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef642ea726cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codename', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codename'),
    schema='public'
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('SUPER_ADMIN', 'ORG_ADMIN', 'COMMISSIONER', 'APPLICANT', name='rolename'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REJECTED', name='tenantstatus'), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nipt', sa.String(length=50), nullable=True),
    sa.Column('doc_path', sa.String(length=500), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='public'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='public'
    )
    op.create_table('applicant_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('applicant_type', sa.Enum('STUDENT', 'BUSINESS', 'ORGANIZATION', 'INDIVIDUAL', 'OTHER', name='applicanttype'), nullable=True),
    sa.Column('has_prev_grant', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('study_level', sa.String(length=50), nullable=True),
    sa.Column('study_status', sa.String(length=50), nullable=True),
    sa.Column('study_year', sa.Integer(), nullable=True),
    sa.Column('faculty', sa.String(length=200), nullable=True),
    sa.Column('study_program', sa.String(length=200), nullable=True),
    sa.Column('university', sa.String(length=200), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('activity_field', sa.String(length=200), nullable=True),
    sa.Column('num_employees', sa.String(length=50), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('org_name', sa.String(length=200), nullable=True),
    sa.Column('org_type', sa.String(length=100), nullable=True),
    sa.Column('org_field', sa.String(length=200), nullable=True),
    sa.Column('num_staff', sa.String(length=50), nullable=True),
    sa.Column('org_founded_year', sa.Integer(), nullable=True),
    sa.Column('reg_number', sa.String(length=100), nullable=True),
    sa.Column('profession', sa.String(length=200), nullable=True),
    sa.Column('experience_years', sa.String(length=50), nullable=True),
    sa.Column('key_skills', sa.Text(), nullable=True),
    sa.Column('portfolio_url', sa.String(length=300), nullable=True),
    sa.Column('cv_path', sa.String(length=500), nullable=True),
    sa.Column('role_title', sa.String(length=200), nullable=True),
    sa.Column('interest_field', sa.String(length=200), nullable=True),
    sa.Column('relevant_link', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='public'
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='public'
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['public.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['public.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission'),
    schema='public'
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles', schema='public')
    op.drop_table('role_permissions', schema='public')
    op.drop_table('password_reset_tokens', schema='public')
    op.drop_table('applicant_profiles', schema='public')
    op.drop_table('users', schema='public')
    op.drop_table('tenants', schema='public')
    op.drop_table('roles', schema='public')
    op.drop_table('permissions', schema='public')
    # ### end Alembic commands ###